export const SOUND_LABELS: Record<string, string> = {
  chime: '🔔 Gentle Chime',
  water: '💧 Running Water',
  alarm: '⏰ Stark Alarm',
  bell: '🔔 Bell',
  birds: '🐦 Birds',
  gong: '🥁 Gong',
  piano: '🎹 Piano',
  afone: '📱 Afone',
  antagonist: '🦹 Antagonist',
  banjo: '🪕 Banjo',
  bassBoost: '🔊 Bass Boost',
  bassSoHard: '🔉 Bass So Hard',
  cyberpunk: '🌃 Cyberpunk',
  darkParadise: '🌌 Dark Paradise',
  morpheus: '💊 Morpheus',
  motivation: '🔥 Motivation Trap',
  viral: '📈 Viral',
  workComplete: '✅ Work Complete',
  breakComplete: '☕ Break Complete',
};
